### ISSUE TITLE
DB Query

### ISSUE THREAD

**Issue by erenilhan** [franklupo/BootstrapTableHelper#1]
Hi, 
firstly thanks for this helpers. I try to use your helpers with laravel 5 db query like this:
<addr>
 $sql = DB::table("groups as g")
                ->leftJoin("groups_translates as gt", "gt.group_id", "=", "g.id")
                ->select("g.updated_at as updated_at", "g.slug", "g.id", "gt.name as name")
                ->where("gt.lang", LaravelLocalization::getCurrentLocale());
</addr>
 and my options like this:
<addr>
    ->setOptions(BootstrapTableHelper::TABLE_SORT_ORDER, 'desc')
            ->setOptions(BootstrapTableHelper::TABLE_DETAIL_VIEW, true)
            ->setOptions(BootstrapTableHelper::TABLE_DETAIL_FORMATTER, "detailFormatter")
            ->addColumn('name', trans("admin/forms.group_name"), true, true)
            ->addColumn('updated_at', trans("admin/forms.updated_at"), true, true)
            ->setColumnAttr("updated_at","data-field","gt.updated_at")
</addr>

its working but search function get error because of in background array_add function explode with ". -(dot)"

**Comment by franklupo** [comment]
Hi,
you can send me error. 

Best regards
