### ISSUE TITLE
Where to place and include BootstrapTableHelper.php

### ISSUE THREAD

**Issue by ghost** [franklupo/BootstrapTableHelper#2]
Can you please advice where to place the BootstrapTableHelper.php file in the laravel structure and how to include the file in the controller or where to place to autoload.

**Comment by erenilhan** [comment]
1-) <strong>Http/Helpers (custom create)</strong>
<img width="398" alt="ekran resmi 2016-01-22 15 09 55" src="https://cloud.githubusercontent.com/assets/5827342/12511485/4e531ad6-c11a-11e5-9845-37a083f7ee20.png">
2-) <strong>composer.json</strong>
<img width="550" alt="ekran resmi 2016-01-22 15 10 27" src="https://cloud.githubusercontent.com/assets/5827342/12511496/5f0fd148-c11a-11e5-8cc2-e9cf20181925.png">
<br/>
and where do you want use "use BootstrapTableHelper;"
<img width="521" alt="ekran resmi 2016-01-22 15 12 43" src="https://cloud.githubusercontent.com/assets/5827342/12511534/9db93128-c11a-11e5-82a1-c4f713bbeee7.png">

**Comment by ghost** [comment]
Great work, I have it working now.

Do you have option included to expand row with sub-table ?

**Comment by erenilhan** [comment]
This is my first function
<img width="847" alt="ekran resmi 2016-01-25 15 05 01" src="https://cloud.githubusercontent.com/assets/5827342/12551716/243dc310-c375-11e5-838f-9d491696c45f.png">
and second (if you want you can merge 2 function)
<img width="870" alt="ekran resmi 2016-01-25 15 05 39" src="https://cloud.githubusercontent.com/assets/5827342/12551743/45a6be44-c375-11e5-96e6-0f69d5976537.png">

**Comment by franklupo** [comment]
I'm thinking about a rewrite module

**Comment by erenilhan** [comment]
its sound good @franklupo
